import { Link } from "react-router";

const TermsConditions = () => {
  return (
    <>
     <div className="min-h-screen bg-neutral-950 px-4 py-10 text-neutral-200">
  <div className="mx-auto max-w-3xl rounded-2xl border border-neutral-800 bg-neutral-900 p-6 shadow-2xl sm:p-10">
    <h1 className="mb-2 text-3xl font-bold text-white">
      Terms & Conditions
    </h1>

    <p className="mb-8 text-sm text-neutral-400">
      Last updated: August 2026
    </p>

    <div className="space-y-7 text-sm leading-7 text-neutral-400">

      <section>
        <h2 className="mb-2 text-xl font-semibold text-white">
          1. Acceptance of Terms
        </h2>
        <p>
          By creating an account and using AI Resume Analyzer, you agree to
          these Terms & Conditions. If you do not agree with any of these
          terms, please do not use the application.
        </p>
      </section>

      <section>
        <h2 className="mb-2 text-xl font-semibold text-white">
          2. Account Registration
        </h2>
        <p>
          You are responsible for providing accurate information when creating
          your account. You are also responsible for keeping your login
          credentials secure and for all activities performed using your
          account.
        </p>
      </section>

      <section>
        <h2 className="mb-2 text-xl font-semibold text-white">
          3. Use of the Application
        </h2>
        <p>
          AI Resume Analyzer is designed to help users analyze resumes,
          identify potential improvements, evaluate skills, and receive
          AI-generated suggestions. The application must be used only for
          lawful and authorized purposes.
        </p>
      </section>

      <section>
        <h2 className="mb-2 text-xl font-semibold text-white">
          4. Resume and Personal Information
        </h2>
        <p>
          Users are responsible for ensuring that the information contained in
          their uploaded resumes is accurate and that they have the necessary
          rights to upload and process such information. Do not upload
          documents containing information that you are not authorized to use.
        </p>
      </section>

      <section>
        <h2 className="mb-2 text-xl font-semibold text-white">
          5. AI-Generated Analysis
        </h2>
        <p>
          Resume scores, recommendations, skill analysis, job-related
          suggestions, and other results generated by the application are
          provided for informational and guidance purposes only. AI-generated
          results may not always be completely accurate and should be reviewed
          by the user before making important career decisions.
        </p>
      </section>

      <section>
        <h2 className="mb-2 text-xl font-semibold text-white">
          6. Account Security
        </h2>
        <p>
          You are responsible for maintaining the confidentiality of your
          account credentials. Do not share your password or account
          information with unauthorized persons. If you believe your account
          has been accessed without permission, take appropriate steps to
          secure your account and contact the system administrator.
        </p>
      </section>

      <section>
        <h2 className="mb-2 text-xl font-semibold text-white">
          7. Privacy and Data
        </h2>
        <p>
          Information provided during registration and while using the
          application may be stored and processed to provide features such as
          resume analysis, account management, and application functionality.
          We aim to protect user information and prevent unauthorized access.
        </p>
      </section>

      <section>
        <h2 className="mb-2 text-xl font-semibold text-white">
          8. Application Availability
        </h2>
        <p>
          We may update, modify, suspend, or temporarily make parts of the
          application unavailable for maintenance, improvements, security
          updates, or other technical reasons.
        </p>
      </section>

      <section>
        <h2 className="mb-2 text-xl font-semibold text-white">
          9. Limitation of Responsibility
        </h2>
        <p>
          AI Resume Analyzer provides resume analysis and career-related
          suggestions as an assistance tool. It does not guarantee employment,
          interviews, job offers, or any specific career outcome. Users are
          responsible for evaluating AI-generated recommendations before
          relying on them.
        </p>
      </section>

      <section>
        <h2 className="mb-2 text-xl font-semibold text-white">
          10. Changes to These Terms
        </h2>
        <p>
          These Terms & Conditions may be updated from time to time. Continued
          use of AI Resume Analyzer after changes are made means that you
          accept the updated terms.
        </p>
      </section>

      <section>
        <h2 className="mb-2 text-xl font-semibold text-white">
          11. Contact
        </h2>
        <p>
          If you have questions or concerns regarding these Terms & Conditions,
          please contact the system administrator.
        </p>
      </section>

    </div>

    <div className="mt-10 border-t border-neutral-800 pt-6">
      <Link
        to="/register"
        className="inline-flex rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white transition-all duration-300 hover:-translate-y-0.5 hover:bg-blue-500 hover:shadow-lg hover:shadow-blue-500/20"
      >
        ← Back to Register
      </Link>
    </div>
  </div>
</div>
    </>
  );
};

export default TermsConditions;
